FROM centos:8
ENV container docker

RUN (cd /lib/systemd/system/sysinit.target.wants/; for i in *; do [ $i == \
systemd-tmpfiles-setup.service ] || rm -f $i; done); \
rm -f /lib/systemd/system/multi-user.target.wants/*;\
rm -f /etc/systemd/system/*.wants/*;\
rm -f /lib/systemd/system/local-fs.target.wants/*; \
rm -f /lib/systemd/system/sockets.target.wants/*udev*; \
rm -f /lib/systemd/system/sockets.target.wants/*initctl*; \
rm -f /lib/systemd/system/basic.target.wants/*;\
rm -f /lib/systemd/system/anaconda.target.wants/*;
VOLUME [ "/sys/fs/cgroup" ]

RUN yum install -y python3

RUN mkdir -p /module/std
WORKDIR /module/std

RUN python3 -m venv env
RUN env/bin/pip install -U pip

COPY requirements.txt requirements.txt
RUN env/bin/pip install -r requirements.txt

COPY requirements.dev.txt requirements.dev.txt
RUN env/bin/pip install -r requirements.dev.txt

ARG PYTEST_INMANTA_DEV
RUN if [ "${PYTEST_INMANTA_DEV}" = true ] ; then env/bin/pip install --pre -U pytest-inmanta -i https://artifacts.internal.inmanta.com/inmanta/dev ; fi

COPY module.yml module.yml
COPY model model
COPY plugins plugins
COPY tests tests

CMD ["/usr/sbin/init"]
